repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [
          app/,
          --ignore-missing-imports,
          --no-strict-optional,
          --allow-untyped-defs,
          --allow-untyped-calls,
          --disable-error-code=type-arg,
          --disable-error-code=arg-type,
          --disable-error-code=attr-defined,
        ]
        additional_dependencies: [
          pydantic>=2.0,
          types-PyYAML,
          types-python-dateutil,
        ]
        files: ^app/
        pass_filenames: false
